assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ 'AfupAdminBundle', 'AfupUserBundle', 'FOSUserBundle' ]
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
#        uglifyjs:
#            bin: /usr/bin/uglifyjs
