security:
    encoders:
        Afup\CoreBundle\Entity\User:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_ADMIN_USER, ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_ADMIN_USER:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_DELETE
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_USER_CREATE

    providers:
        main:
            entity: { class: Afup\Model\Member, property: username }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                use_referer: true
            logout:
                path:   /admin/logout
                target: /admin

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN }
