security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_ADMIN_USER, ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_ADMIN_USER:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_DELETE
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_USER_CREATE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        member:
            pattern: ^/membre
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /membre/login_check
                login_path: /membre/login
                use_referer: true
                default_target_path: /membre/
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/membre/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/membre/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/membre/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/membre, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
