imports:
    - { resource: parameters.yml }
    - { resource: extensions/admin.yml }
    - { resource: extensions/assets.yml }
    - { resource: extensions/database.yml }
    - { resource: extensions/framework.yml }
    - { resource: extensions/mailer.yml }
    - { resource: extensions/security.yml }
    - { resource: extensions/template_engine.yml }
    - { resource: extensions/user.yml }
