parameters:
#    afup_core.example.class: Afup\CoreBundle\Example

services:
#    afup_core.example:
#        class: %afup_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
