<?php

namespace Afup\SubscriptionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorporationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationRepository extends EntityRepository
{
}
