<?php

namespace Afup\SubscriptionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalSubscriptionRepository extends EntityRepository
{
}
